<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MMLib.OpenApiForYarp" Version="1.1.0" />
		<PackageReference Include="MMLib.OpenApiForYarp.Scalar" Version="1.1.0" />
		<PackageReference Include="Yarp.ReverseProxy" Version="2.3.0" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.2" />
		<PackageReference Include="Serilog.AspNetCore" Version="10.0.1-dev-02312" />
		<PackageReference Include="Serilog.Formatting.Compact" Version="3.0.0" />
		<PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.19.1" />
		<PackageReference Include="OpenTelemetry.Exporter.Prometheus.AspNetCore" Version="1.19.1-beta.1" />
		<PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.19.1" />
		<PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.19.0" />
		<PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.19.0" />
		<PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.19.0" />
	</ItemGroup>

</Project>