<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="../Domain/Bookings.Domain.csproj" />
		<ProjectReference Include="..\..\..\EventBroker.Contracts\Enums\Enums.csproj" />
		<ProjectReference Include="..\..\..\EventBroker.Contracts\Messaging\Messaging.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="16.2.0" />
		<PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.2.0" />
		<PackageReference Include="Confluent.Kafka" Version="2.2.0" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.2" />
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.2" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.2" />
	</ItemGroup>

</Project>