<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="../Domain/Bookings.Domain.csproj" />
		<ProjectReference Include="..\..\..\EventBroker.Contracts\Enums\Enums.csproj" />
		<ProjectReference Include="..\..\..\EventBroker.Contracts\Messaging\Messaging.csproj" />
</ItemGroup>

	<ItemGroup>
		
	  		<PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.12" />
		
	  		<PackageReference Include="Confluent.Kafka" Version="2.2.0" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.7" />
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.7" />
		<PackageReference Include="AutoMapper" Version="16.1.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.17" />
	</ItemGroup>

	</Project>