<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>1e2274de-06ae-4ce3-9ce4-76d11d2b314c</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..\..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Application/Users.Application.csproj" />
    <ProjectReference Include="../Infrastructure/Users.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.18" />
	<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.16" />
	  
	<PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.19.1" />
	<PackageReference Include="OpenTelemetry.Exporter.Prometheus.AspNetCore" Version="1.19.1-beta.1" />
	<PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.19.1" />
	<PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.19.0" />
	<PackageReference Include="OpenTelemetry.Instrumentation.EntityFrameworkCore" Version="1.19.1-beta.1" />
	<PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.19.0" />
	<PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.19.0" />

	<PackageReference Include="Serilog.AspNetCore" Version="10.0.1-dev-02312" />
	<PackageReference Include="Serilog.Formatting.Compact" Version="3.0.0" />
  </ItemGroup>

</Project>